"""Bounded parser for user-supplied lyric-bearing ChordPro song sheets."""

from pathlib import Path
import re


MAX_SONG_BYTES = 1024 * 1024
MAX_SONG_LINE_BYTES = 16 * 1024


class ChordProSongError(ValueError):
    """A safe, user-facing failure while reading a Song sidecar."""

    def __init__(self, message, status_code=422):
        super().__init__(message)
        self.status_code = status_code


_DIRECTIVE_RE = re.compile(
    r"^\{([A-Za-z][A-Za-z0-9_]*)(?:\s*:\s*((?:\\[\\\[\]{}]|[^{}])*))?\}$"
)
# ChordFlask-specific, non-display synchronization metadata generated by
# ``chordflask-genlyrics``. It lives in ordinary custom ChordPro directives so
# chord markers stay normal ChordPro names and other readers simply ignore it:
#
#     {x_chordflask_beats: 17,23}
#     {x_chordflask_end: 40}
#     [G]some lyric [Am]more lyric
#
# ``x_chordflask_beats`` lists the analyzed start beat for each chord marker in
# the immediately following line, in order. ``x_chordflask_end`` closes the
# final marker range. The parser turns this compact line metadata into explicit
# ``[start_beat, end_beat)`` ranges on the chord runs, so browser code only has
# to look up the range containing the authoritative playback beat. The analysis
# JSON remains the only chord/rhythm truth.
_SYNC_BEATS_DIRECTIVE = "x_chordflask_beats"
_SYNC_END_DIRECTIVE = "x_chordflask_end"
_ESCAPED_CHARACTERS = frozenset("[]{}\\")
_METADATA_DIRECTIVES = frozenset(
    ("title", "artist", "subtitle", "key", "capo", "x_chordflask_track")
)
_SECTION_STARTS = {
    "start_of_verse": ("verse", "Verse"),
    "sov": ("verse", "Verse"),
    "start_of_chorus": ("chorus", "Chorus"),
    "soc": ("chorus", "Chorus"),
    "start_of_bridge": ("bridge", "Bridge"),
    "sob": ("bridge", "Bridge"),
}
_SECTION_ENDS = {
    "end_of_verse": "verse",
    "eov": "verse",
    "end_of_chorus": "chorus",
    "eoc": "chorus",
    "end_of_bridge": "bridge",
    "eob": "bridge",
}
_COMMENTS = {
    "comment": "normal",
    "c": "normal",
    "comment_italic": "italic",
    "ci": "italic",
    "comment_box": "box",
    "cb": "box",
}


def _unescape(value):
    output = []
    index = 0
    while index < len(value):
        if (
            value[index] == "\\"
            and index + 1 < len(value)
            and value[index + 1] in _ESCAPED_CHARACTERS
        ):
            index += 1
        output.append(value[index])
        index += 1
    return "".join(output)


def _parse_beat_list(value):
    parts = [part.strip() for part in value.split(",")]
    if not parts or any(not part for part in parts):
        return None
    try:
        beats = [int(part) for part in parts]
    except ValueError:
        return None
    return beats if all(beat >= 0 for beat in beats) else None


def _parse_beat_end(value):
    try:
        end = int(value.strip())
    except ValueError:
        return None
    return end if end >= 0 else None


def _attach_sync_map(block, beats, end):
    """Attach validated beat ranges to a parsed line, or nothing.

    The count of analyzed beats must exactly match the number of chord markers
    in the line and the beats must be strictly increasing and end after the
    last one. Otherwise the line is left without a map and renders statically,
    so a manually edited ``.cho`` never gains invented synchronization.
    """
    if block.get("type") != "line" or not beats or end is None:
        return
    chord_runs = [run for run in block["runs"] if run["chord"] is not None]
    if len(chord_runs) != len(beats):
        return
    if any(beats[index] >= beats[index + 1] for index in range(len(beats) - 1)):
        return
    if end <= beats[-1]:
        return
    ends = beats[1:] + [end]
    for run, start_beat, end_beat in zip(chord_runs, beats, ends, strict=True):
        run["start_beat"] = start_beat
        run["end_beat"] = end_beat


def _literal_line(line):
    return {"type": "line", "runs": [{"chord": None, "lyric": _unescape(line)}]}


def _parse_lyric_line(line):
    runs = []
    lyric = []
    chord = None
    index = 0
    saw_marker = False

    while index < len(line):
        character = line[index]
        if character == "\\" and index + 1 < len(line):
            escaped = line[index + 1]
            if escaped in _ESCAPED_CHARACTERS:
                lyric.append(escaped)
                index += 2
                continue
        if character == "]":
            return _literal_line(line)
        if character != "[":
            lyric.append(character)
            index += 1
            continue

        marker = []
        marker_index = index + 1
        closed = False
        while marker_index < len(line):
            marker_character = line[marker_index]
            if marker_character == "\\" and marker_index + 1 < len(line):
                escaped = line[marker_index + 1]
                if escaped in _ESCAPED_CHARACTERS:
                    marker.append(escaped)
                    marker_index += 2
                    continue
            if marker_character == "[":
                return _literal_line(line)
            if marker_character == "]":
                closed = True
                break
            marker.append(marker_character)
            marker_index += 1
        if not closed or not "".join(marker).strip():
            return _literal_line(line)

        if lyric or chord is not None:
            runs.append({"chord": chord, "lyric": "".join(lyric)})
        chord = "".join(marker)
        lyric = []
        saw_marker = True
        index = marker_index + 1

    if saw_marker:
        runs.append({"chord": chord, "lyric": "".join(lyric)})
        return {"type": "line", "runs": runs}
    return _literal_line(line)


def parse_chordpro(text):
    """Parse the phase-1 ChordPro subset into JSON-serializable records."""
    metadata = {}
    blocks = []
    section_stack = []
    pending_beats = None
    pending_end = None

    for source_line in text.splitlines():
        if not source_line:
            blocks.append({"type": "blank"})
            pending_beats = None
            pending_end = None
            continue

        if source_line.startswith("{"):
            match = _DIRECTIVE_RE.fullmatch(source_line)
            if match is None:
                blocks.append(_literal_line(source_line))
                pending_beats = None
                pending_end = None
                continue
            name = match.group(1).lower()
            value = _unescape(match.group(2) or "")
            if name == _SYNC_BEATS_DIRECTIVE:
                pending_beats = _parse_beat_list(value)
                continue
            if name == _SYNC_END_DIRECTIVE:
                pending_end = _parse_beat_end(value)
                continue
            pending_beats = None
            pending_end = None
            if name in _METADATA_DIRECTIVES:
                if match.group(2) is None:
                    blocks.append(_literal_line(source_line))
                else:
                    metadata[name] = value
                continue
            if name in _SECTION_STARTS:
                section, default_heading = _SECTION_STARTS[name]
                section_stack.append(section)
                blocks.append({
                    "type": "section_start",
                    "section": section,
                    "heading": value or default_heading,
                })
                continue
            if name in _SECTION_ENDS:
                section = _SECTION_ENDS[name]
                if match.group(2) is not None or not section_stack or section_stack[-1] != section:
                    blocks.append(_literal_line(source_line))
                else:
                    section_stack.pop()
                    blocks.append({"type": "section_end", "section": section})
                continue
            if name in _COMMENTS:
                if match.group(2) is None:
                    blocks.append(_literal_line(source_line))
                else:
                    blocks.append({"type": "comment", "style": _COMMENTS[name], "text": value})
                continue
            continue

        block = _parse_lyric_line(source_line)
        _attach_sync_map(block, pending_beats, pending_end)
        blocks.append(block)
        pending_beats = None
        pending_end = None

    return {"metadata": metadata, "blocks": blocks}


def read_chordpro(path):
    """Read strict bounded UTF-8 ChordPro input and return parsed records."""
    path = Path(path)
    try:
        with path.open("rb") as song_file:
            content = song_file.read(MAX_SONG_BYTES + 1)
    except OSError as error:
        raise ChordProSongError("Song sheet could not be read") from error

    if len(content) > MAX_SONG_BYTES:
        raise ChordProSongError("Song sheet is too large", status_code=413)
    if not content:
        raise ChordProSongError("Song sheet is empty")
    for line in content.splitlines():
        if len(line) > MAX_SONG_LINE_BYTES:
            raise ChordProSongError(
                "Song sheet contains an oversized line", status_code=413
            )
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError as error:
        raise ChordProSongError("Song sheet is not valid UTF-8") from error
    if not text.strip():
        raise ChordProSongError("Song sheet is empty")
    return parse_chordpro(text)
