from chordflask_base import (
    ANALYSIS_DIR_NAME as ANALYSIS_DIR_NAME,
    ANALYSIS_SAMPLE_RATE as ANALYSIS_SAMPLE_RATE,
    DEFAULT_CHORD_TRACK as DEFAULT_CHORD_TRACK,
    DEFAULT_RHYTHM_TRACK as DEFAULT_RHYTHM_TRACK,
)

LEGACY_ANALYSIS_DIR_NAME = ".chordy"
ALLOWED_MEDIA_ROOTS_ENV = "CHORDFLASK_MEDIA_ROOTS"
LEGACY_MEDIA_ROOTS_ENV = "CHORDIFIER_MEDIA_ROOTS"
LISTEN_ENV = "CHORDFLASK_LISTEN"
LEGACY_LISTEN_ENV = "CHORDIFIER_LISTEN"
PORT_ENV = "CHORDFLASK_PORT"
LEGACY_PORT_ENV = "CHORDIFIER_PORT"
DEBUG_ENV = "CHORDFLASK_DEBUG"
LEGACY_DEBUG_ENV = "CHORDIFIER_DEBUG"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 5000
SUPPORTED_MEDIA_SUFFIXES = frozenset({".mp3", ".mp4", ".webm"})
MEDIA_SUFFIX_PRIORITY = {".mp4": 0, ".webm": 1, ".mp3": 2}
